version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - 8000:8000
    networks:
      - expense-tracker
    restart: unless-stopped
    env_file: docker.env
    depends_on:
      - db

  db:
    image: library/postgres:11.3-alpine
    restart: unless-stopped
    ports:
      - 10000:5432
    networks:
      - expense-tracker
    environment:
      - POSTGRES_USER=expensetracker
      - POSTGRES_PASSWORD=expensetracker

networks:
  expense-tracker:
    driver: bridge
